[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 17

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["*"]
jwt_expiry = 3600
enable_signup = true
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
minimum_password_length = 8
password_requirements = ""

[auth.email]
enable_signup = true
enable_confirmations = false
double_confirm_changes = true
secure_password_change = true
max_frequency = "1s"
otp_length = 6
otp_expiry = 3600

[auth.sessions]
timebox = "24h"
inactivity_timeout = "8h"

[auth.mfa]
max_enrolled_factors = 10

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.mfa.phone]
enroll_enabled = false
verify_enabled = false

[auth.rate_limit]
email_sent = 2
sms_sent = 30
token_refresh = 150
sign_in_sign_ups = 30
token_verifications = 30
